title: klask.io
show_downloads: true
baseurl: "https://github.com/klask-io/klask-io"
theme: jekyll-theme-cayman
lsi: false
safe: true
source: ["https://github.com/klask-io/klask-io"]
incremental: false
highlighter: rouge

# About/contact
author:
  name:       Jérémie H.
  url:        http://klask.io
