title: klask.io
show_downloads: false
theme: jekyll-theme-architect
url: "http://klask.io"
lsi: true
safe: false
source: ['https://github.com/klask-io/klask-io']
incremental: false
highlighter: rouge

# About/contact
author:
  name:       Jérémie H.
  url:        http://klask.io

# Google services
google_analytics: UA-92691122-2
